In [32]:
import pandas as pd
import numpy as np

In [33]:
ean = pd.read_csv('Fashione EAN 05-10-26.csv', dtype=str)
ean = ean[['PLU', 'Style', 'Colour', 'Size', 'EAN']]
ean.head()

          PLU Style      Colour Size  EAN
0  0002875800   007    BLK/BLUE    S  NaN
1  0002875801   007    BLK/BLUE    M  NaN
2  0002875802   007    BLK/BLUE    L  NaN
3  0002875803   007    BLK/BLUE   XL  NaN
4  0002876200   007  BLK/PURPLE    S  NaN

In [34]:
loc = pd.read_csv('eeb210aa-b068-4f28-8dbc-55eadb641663.csv', dtype=str)
loc['ImageURL'] = loc['ThumbnailUrl']
loc['PLU'] = loc['SKU']
loc['Pick Location'] = loc['WarehouseLocation']
loc = loc[['PLU', 'Pick Location', 'ImageURL']]

ean = pd.merge(ean, loc, on='PLU', how='left')

loc

,PLU,Pick Location,ImageURL
0,0000068900,A-24C,https://cdn.shopify.com/s/files/1/0988/1567/27...
1,0000069500,A-23C,https://cdn.shopify.com/s/files/1/0988/1567/27...
2,0000069700,B-02C,https://cdn.shopify.com/s/files/1/0988/1567/27...
3,0000071400,A-25C/26C,https://cdn.shopify.com/s/files/1/0988/1567/27...
4,0000071500,A-25C/26C,https://cdn.shopify.com/s/files/1/0988/1567/27...
...,...,...,...
15370,852500,NaN,NaN
15371,852700,NaN,NaN
15372,852900,NaN,NaN
15373,853300,NaN,NaN
15374,Voucher,NaN,NaN

In [35]:
wr = pd.read_csv('Fonz Product List 07-10-26.csv', skiprows=1, dtype=str)
wr = wr[['PLU', 'FashBCode']]

ean = pd.merge(ean, wr, on='PLU', how='left')

ean.head()

,PLU,Style,Colour,Size,EAN,Pick Location,ImageURL,FashBCode
0,0002875800,007,BLK/BLUE,S,NaN,C-02D,https://cdn.shopify.com/s/files/1/0988/1567/27...,9900028758000
1,0002875801,007,BLK/BLUE,M,NaN,C-02D,https://cdn.shopify.com/s/files/1/0988/1567/27...,9900028758017
2,0002875802,007,BLK/BLUE,L,NaN,C-02D,https://cdn.shopify.com/s/files/1/0988/1567/27...,9900028758024
3,0002875803,007,BLK/BLUE,XL,NaN,NaN,NaN,9900028758031
4,0002876200,007,BLK/PURPLE,S,NaN,C-02D,https://cdn.shopify.com/s/files/1/0988/1567/27...,9900028762007

In [36]:
ean['FashBCode'] = ean['FashBCode'].fillna('-')
ean['EAN'] = ean['EAN'].fillna('-')

In [37]:
ean.to_csv('Return Inventory File.csv', index=False)