In [8]:
import pandas as pd
import numpy as np

In [9]:
ean = pd.read_csv('Fashione EAN 27-10-25.csv', dtype=str)
ean = ean[['PLU', 'Style', 'Colour', 'Size', 'EAN']]
ean.head()

          PLU Style      Colour Size  EAN
0  0002875800   007    BLK/BLUE    S  NaN
1  0002875801   007    BLK/BLUE    M  NaN
2  0002875802   007    BLK/BLUE    L  NaN
3  0002875803   007    BLK/BLUE   XL  NaN
4  0002876200   007  BLK/PURPLE    S  NaN

In [10]:
loc = pd.read_csv('vs_debenhams_offers_upload_export_20251029-174854_leather-company.csv', dtype=str)
temp = loc['Parent Product Images'].str.split('\n', expand=True)
loc['ImageURL'] = temp[0]
loc['PLU'] = loc['Child Reference']
loc = loc[['PLU', 'Pick Location', 'ImageURL']]

ean = pd.merge(ean, loc, on='PLU', how='left')

In [11]:
wr = pd.read_excel('Fonz Product list export.xlsx', skiprows=1, dtype=str)
wr = wr[['PLU', 'FashBCode']]

ean = pd.merge(ean, wr, on='PLU', how='left')

ean.head()

,PLU,Style,Colour,Size,EAN,Pick Location,ImageURL,FashBCode
0,0002875800,007,BLK/BLUE,S,NaN,C-03E,https://www.leathercompany.co.uk/images/produc...,9900028758000
1,0002875801,007,BLK/BLUE,M,NaN,C-03E,https://www.leathercompany.co.uk/images/produc...,9900028758017
2,0002875802,007,BLK/BLUE,L,NaN,C-03E,https://www.leathercompany.co.uk/images/produc...,9900028758024
3,0002875803,007,BLK/BLUE,XL,NaN,NaN,NaN,9900028758031
4,0002876200,007,BLK/PURPLE,S,NaN,C-03E,https://www.leathercompany.co.uk/images/produc...,9900028762007

In [12]:
ean['FashBCode'] = ean['FashBCode'].fillna('-')
ean['EAN'] = ean['EAN'].fillna('-')

In [13]:
ean.to_csv('Return Inventory File.csv', index=False)